networks:
    app_network:
        external: true
        name: ${APP_DOCKER_NETWORK}

volumes:
    mailpit_data:

services:

    mailpit:
        image: axllent/mailpit:v1.27
        hostname: mailpit
        container_name: ${COMPOSE_PROJECT_NAME}-mailpit
        ports:
            - "${MAILPIT_DASHBOARD_PORT:-8025}:8025"
        volumes:
            - mailpit_data:/data
        environment:
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        networks:
            app_network:
