name: Code Quality Analysis

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    # Run this for everything EXCEPT non-merged closed PRs
    if: (!(github.event.action == 'closed' && github.event.pull_request.merged != true) || !contains(github.event.head_commit.message, 'skip ci'))
    name: "Test - PHP: ${{ matrix.php }} - Laravel - ${{ matrix.stability }}"
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_DATABASE: testing
      DB_USERNAME: root
      DB_PASSWORD: password

    strategy:
        fail-fast: false
        matrix:
            php: ['8.4']
            stability: [prefer-stable, prefer-lowest]

    services:
      mysql:
        image: mysql:8.4
        env:
            MYSQL_ALLOW_EMPTY_PASSWORD: false
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: testing
        ports:
            - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      redis:
        image: redis:8.2-alpine
        ports:
            - 6379/tcp
        options: >-
            --health-cmd "redis-cli ping"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis

      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pcntl, mbstring, dom, fileinfo, pdo, json, mysqli, pdo_mysql, intl, gd, redis
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: pcov

      - name: Start Typesense
        uses: jirevwe/typesense-github-action@v1.0.1
        with:
          typesense-api-key: some-api-key
          typesense-port: 8108

      - name: Install Composer Dependencies
        run: |
            composer install --no-interaction --no-scripts --no-progress --prefer-dist --ansi --optimize-autoloader
            composer run-script post-root-package-install
            composer run-script post-autoload-dump

      - name: Generate APP_KEY
        run: |
          cp .env.example .env
          cp .env.testing.example .env.testing
          php artisan key:generate
          php artisan key:generate --env=testing

      - name: Run Testing
        run: composer populate-db && composer tests-ci -- --min=49
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
          REDIS_PORT: ${{ job.services.redis.ports['6379'] }}

      - name: Generate Test Coverage Badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
      #   if: github.event.pull_request.merged == true
        with:
          report: report/clover-coverage.xml
          report_type: clover
          coverage_badge_path: 'badge-coverage.svg'
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  phpmd:
    name: PHP Mess Detector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none
          tools: phpmd

      - name: Run PHP Mess Detector
        run: phpmd app github phpmd.xml -v

  pint:
    name: Laravel Pint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none
          tools: pint

      - name: Run Laravel Pint
        run: pint --test

  larastan:
    name: Larastan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none
          tools: phpstan

      - name: Validate and install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-progress

      - name: Run Larastan
        run: phpstan analyse --memory-limit=1G -v

  insights:
    name: PHP Insights
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none
          tools: phpstan

      - name: Validate and install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-progress

      - name: Run PHP Insights
        run: php artisan insights --no-interaction --ansi --format=github-action -v
